version: "3"
services:

  # backend 
  bio-backend:
    container_name: bio-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: >
      sh "./mongorestore.sh"
    ports:
    - "3000:3000"
    links:
    - mongo
  #mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27018:27017"
    volumes:
    - type: bind
      source: ./mongorestore.sh
      target: /docker-entrypoint-initdb.d/mongorestore.sh
  
  # frontend
  bio-frontend:
    container_name: bio-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
    - "80:80"

# services:
#   webapp:
#     build: https://github.com/mycompany/example.git#branch_or_tag:subdirectory