FROM golang:1.19.4 AS builder

### Copy Go code
WORKDIR /src/
COPY . .

### Build executables
RUN go build -o /app/webapi ./cmd/webapi


### Create final container
FROM debian:bullseye

### Inform Docker about which port is used
EXPOSE 3000 4000

### Import file ./conf/config.yml
#COPY nginx.conf /etc/nginx/conf.d/default.conf
### Copy the build executable from the builder image
WORKDIR /app/
ADD conf ./conf
COPY --from=builder /app/webapi ./

### Executable command
CMD ["/app/webapi"]