Name:     "Biologia"
Version:  "a0.0.2"
Server:
  ServerPort:     3000
  ServerIp:       "2.35.186.59"
  ServerAddress:  ":3000"
  ServerConfig:
    ReadTimeout:      "5s"
    WriteTimeout:     "5s"
    ShutdownTimeout:  "5s"